import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Header } from '@/client/components/common';

const pretendard = localFont({
	src: '../../public/fonts/PretendardVariable.woff2',
	variable: '--font-pretendard',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={pretendard.variable}>
				<Header />
				<div className="py-20">

				{children}
				</div>
			</body>
		</html>
	);
}
